[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://jsonplaceholder.typicode.com"
  NEXT_PUBLIC_OPENAI_API_KEY = "demo_key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200