[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd frontend && npm install"]

[phases.build]  
cmds = ["cd frontend && npm run railway-build"]

[start]
cmd = "cd frontend && npm run railway-start"